# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('moneycash', '0002_auto_20150408_1021'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(max_length=25, null=True, verbose_name=b'codigo', blank=True)),
                ('name', models.CharField(max_length=100, verbose_name=b'nombre')),
                ('activo', models.BooleanField(default=True)),
                ('encargado', models.CharField(default=b'', max_length=100)),
                ('unidad_ejecutora', models.CharField(default=b'', max_length=10)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(max_length=25, null=True, verbose_name=b'codigo', blank=True)),
                ('name', models.CharField(max_length=100, verbose_name=b'nombre')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('identificacion', models.CharField(max_length=25, null=True, verbose_name=b'ruc/cedula', blank=True)),
                ('telefono', models.CharField(max_length=100, null=True, blank=True)),
                ('direccion', models.CharField(max_length=100, null=True, blank=True)),
                ('code', models.CharField(max_length=25, null=True, verbose_name=b'codigo', blank=True)),
                ('name', models.CharField(max_length=100, verbose_name=b'nombre')),
                ('activo', models.BooleanField(default=True)),
                ('limite_credito', models.FloatField(default=0, null=True, verbose_name=b'limite de credito', blank=True)),
                ('saldo', models.FloatField(default=0, verbose_name=b'saldo inicial', blank=True)),
                ('plazo', models.PositiveIntegerField(default=0, help_text=b'plazo de credito expresado en cantidad de dias', null=True)),
                ('contacto', models.CharField(max_length=75, null=True, blank=True)),
                ('nombre_area', models.CharField(max_length=75, null=True, blank=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(max_length=25, null=True, verbose_name=b'codigo', blank=True)),
                ('name', models.CharField(max_length=100, verbose_name=b'nombre')),
                ('activo', models.BooleanField(default=True)),
                ('modelo', models.CharField(default=b'', max_length=30)),
                ('serie', models.CharField(default=b'', max_length=30)),
                ('velocidad', models.PositiveIntegerField(default=0, verbose_name=b'velocidad del equipo')),
                ('precio_copia', models.FloatField(null=True, blank=True)),
                ('costo_copia', models.FloatField(null=True, blank=True)),
                ('contador_inicial', models.PositiveIntegerField(default=0, help_text=b'contador que tenia el equipo al momento de la compra')),
                ('contador_actual', models.PositiveIntegerField(default=0)),
                ('vida_util', models.PositiveIntegerField(default=1000000)),
                ('costo_compra', models.FloatField(null=True, verbose_name=b'costo de compra', blank=True)),
                ('depreciacion_copia', models.FloatField(null=True, verbose_name=b'depreciacion por copia', blank=True)),
                ('valor_depreciado', models.FloatField(null=True, verbose_name=b'total depreciado', blank=True)),
                ('precio_venta', models.FloatField(null=True, verbose_name=b'valor en libros', blank=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='equipo_periodo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('contador_inicial', models.PositiveIntegerField()),
                ('contador_final', models.PositiveIntegerField()),
                ('copias', models.PositiveIntegerField(default=0, null=True, blank=True)),
                ('equipo', models.ForeignKey(to='produccion.Equipo')),
            ],
            options={
                'verbose_name': 'equipo',
                'verbose_name_plural': 'equipos en produccion',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('fecha', models.DateField()),
                ('numero', models.PositiveIntegerField(null=True, blank=True)),
                ('autorizado', models.BooleanField(default=True)),
                ('impreso', models.BooleanField(default=False)),
                ('contabilizado', models.BooleanField(default=False)),
                ('entregado', models.BooleanField(default=False)),
                ('fecha_vence', models.DateField(help_text=b'si se deja en blanco se aplica el plazo del provedor', null=True, verbose_name=b'fecha de vencimiento', blank=True)),
                ('comentarios', models.TextField(max_length=400, null=True, blank=True)),
                ('tipo', models.CharField(default=b'CR', max_length=2, verbose_name=b'tipo de pago de la compra', choices=[(b'CO', b'CONTADO'), (b'CR', b'CREDITO')])),
                ('subtotal', models.FloatField(default=0.0)),
                ('descuento', models.FloatField(default=0.0)),
                ('iva', models.FloatField(default=0.0)),
                ('exento_iva', models.BooleanField(default=False)),
                ('x_iva', models.FloatField(default=100, blank=True)),
                ('ir', models.FloatField(default=0.0, verbose_name=b'retencion del ir')),
                ('exento_ir', models.BooleanField(default=False)),
                ('x_ir', models.FloatField(default=100, blank=True)),
                ('al', models.FloatField(default=0.0, verbose_name=b'retencion de la alcaldia')),
                ('exento_al', models.BooleanField(default=False, verbose_name=b'exento alcaldia')),
                ('x_al', models.FloatField(default=100, blank=True)),
                ('total', models.FloatField(default=0.0)),
                ('abonado', models.FloatField(default=0.0)),
                ('saldo', models.FloatField(default=0.0)),
                ('tc', models.FloatField(default=0.0, null=True)),
                ('cliente', models.ForeignKey(to='produccion.Cliente')),
                ('moneda', models.ForeignKey(related_name='produccion_factura_moneda', default=1, to='moneycash.Moneda')),
                ('periodo', models.ForeignKey(related_name='produccion_factura_periodo', blank=True, to='moneycash.Periodo', null=True)),
                ('sucursal', models.ForeignKey(related_name='produccion_factura_sucursal', blank=True, to='moneycash.Sucursal', null=True)),
                ('user', models.ForeignKey(related_name='produccion_factura_user', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ['-numero'],
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='factura_detalle',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('cantidad', models.FloatField(default=1)),
                ('precio', models.FloatField(default=0.0)),
                ('descuento', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('area', models.ForeignKey(blank=True, to='produccion.Area', null=True)),
                ('factura', models.ForeignKey(to='produccion.Factura')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'productos o servicios',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(max_length=25, null=True, verbose_name=b'codigo', blank=True)),
                ('name', models.CharField(max_length=100, verbose_name=b'nombre')),
                ('activo', models.BooleanField(default=True)),
                ('precio', models.FloatField(default=0.0)),
                ('categoria', models.ForeignKey(to='produccion.Categoria')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(max_length=25, null=True, verbose_name=b'codigo', blank=True)),
                ('name', models.CharField(max_length=100, verbose_name=b'nombre')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('fecha', models.DateField()),
                ('numero', models.PositiveIntegerField(null=True, blank=True)),
                ('autorizado', models.BooleanField(default=True)),
                ('impreso', models.BooleanField(default=False)),
                ('contabilizado', models.BooleanField(default=False)),
                ('entregado', models.BooleanField(default=False)),
                ('copias', models.FloatField(default=0.0)),
                ('importe', models.FloatField(default=0.0)),
                ('tc', models.FloatField(default=0.0)),
                ('area', models.ForeignKey(to='produccion.Area')),
                ('periodo', models.ForeignKey(related_name='produccion_recibo_periodo', blank=True, to='moneycash.Periodo', null=True)),
                ('sucursal', models.ForeignKey(related_name='produccion_recibo_sucursal', blank=True, to='moneycash.Sucursal', null=True)),
                ('user', models.ForeignKey(related_name='produccion_recibo_user', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ['-numero'],
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='recibo_detalle',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('copias', models.FloatField(default=0.0)),
                ('precio', models.FloatField(default=0.0)),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField()),
                ('equipo', models.ForeignKey(to='produccion.Equipo')),
                ('recibo', models.ForeignKey(to='produccion.Recibo')),
            ],
            options={
                'verbose_name': 'equipo',
                'verbose_name_plural': 'detalle de copias por equipo',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(max_length=25, null=True, verbose_name=b'codigo', blank=True)),
                ('name', models.CharField(max_length=100, verbose_name=b'nombre')),
                ('activo', models.BooleanField(default=True)),
                ('direccion', models.TextField(max_length=250, null=True, blank=True)),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='factura_detalle',
            name='item',
            field=models.ForeignKey(to='produccion.Item'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='equipo',
            name='marca',
            field=models.ForeignKey(to='produccion.Marca'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='equipo',
            name='ubicacion',
            field=models.ForeignKey(blank=True, to='produccion.Ubicacion', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='area',
            name='cliente',
            field=models.ForeignKey(to='produccion.Cliente'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='area',
            name='equipos',
            field=models.ManyToManyField(to='produccion.Equipo', verbose_name=b'equipos que usa el area'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='area',
            name='item',
            field=models.ForeignKey(verbose_name=b'plan de facturarion', blank=True, to='produccion.Item', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='area',
            name='ubicacion',
            field=models.ForeignKey(to='produccion.Ubicacion'),
            preserve_default=True,
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('moneycash.periodo',),
        ),
        migrations.AddField(
            model_name='equipo_periodo',
            name='periodo',
            field=models.ForeignKey(to='produccion.Periodo'),
            preserve_default=True,
        ),
    ]
