# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('fecha', models.DateField()),
                ('numero', models.PositiveIntegerField(null=True, blank=True)),
                ('autorizado', models.BooleanField(default=False)),
                ('impreso', models.BooleanField(default=False)),
                ('contabilizado', models.BooleanField(default=False)),
                ('entregado', models.BooleanField(default=False)),
                ('apertura', models.DateTimeField(null=True, blank=True)),
                ('saldo_inicial', models.FloatField(default=0)),
                ('cierre', models.DateTimeField(null=True, blank=True)),
                ('saldo_final', models.FloatField(default=0)),
                ('cerrado', models.BooleanField(default=False)),
                ('caja', models.ForeignKey(to='moneycash.Caja')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('identificacion', models.CharField(max_length=25, null=True, blank=True)),
                ('telefono', models.CharField(max_length=100, null=True, blank=True)),
                ('direccion', models.CharField(max_length=100, null=True, blank=True)),
                ('bodegas', models.ManyToManyField(to='moneycash.Bodega', null=True, blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('cargo', models.CharField(max_length=100, null=True, verbose_name=b'cargo que ocupa', blank=True)),
                ('telefono', models.CharField(max_length=50, null=True, blank=True)),
                ('email', models.EmailField(max_length=75, null=True, blank=True)),
                ('cliente', models.ForeignKey(to='moneycash.Cliente')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('numero_cuenta', models.CharField(max_length=25)),
                ('limite_credito', models.FloatField()),
                ('plazo', models.PositiveIntegerField()),
                ('saldo', models.FloatField(null=True, blank=True)),
                ('cliente', models.ForeignKey(to='moneycash.Cliente')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('fecha', models.DateField()),
                ('numero', models.PositiveIntegerField(null=True, blank=True)),
                ('autorizado', models.BooleanField(default=False)),
                ('impreso', models.BooleanField(default=False)),
                ('contabilizado', models.BooleanField(default=False)),
                ('entregado', models.BooleanField(default=False)),
                ('monto', models.FloatField()),
                ('banco', models.ForeignKey(to='moneycash.Banco')),
                ('caja', models.ForeignKey(related_name=b'moneycash_deposito_caja', blank=True, to='moneycash.Caja', null=True)),
                ('cierre_caja', models.ForeignKey(related_name=b'moneycash_deposito_cierre_caja', blank=True, to='moneycash.CierreCaja', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='detalle_pago',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('monto', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('saldo', models.FloatField(default=0)),
                ('numero_cheque', models.CharField(max_length=25, null=True, blank=True)),
                ('numero_transferencia', models.CharField(max_length=25, null=True, blank=True)),
                ('banco', models.ForeignKey(blank=True, to='moneycash.Banco', null=True)),
                ('cuenta', models.ForeignKey(blank=True, to='moneycash.Cuenta', null=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('fecha', models.DateField()),
                ('numero', models.PositiveIntegerField(null=True, blank=True)),
                ('autorizado', models.BooleanField(default=False)),
                ('impreso', models.BooleanField(default=False)),
                ('contabilizado', models.BooleanField(default=False)),
                ('entregado', models.BooleanField(default=False)),
                ('exento_iva', models.BooleanField(default=False)),
                ('exento_iva_monto', models.FloatField(null=True, verbose_name=b'porcentaje autorizado por la dgi', blank=True)),
                ('alcaldia', models.BooleanField(default=False)),
                ('retencion_ir', models.BooleanField(default=False)),
                ('subtotal', models.FloatField(default=0)),
                ('descuento', models.FloatField(default=0)),
                ('iva', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('retencion', models.FloatField(default=0)),
                ('costos', models.FloatField(default=0)),
                ('utilidad', models.FloatField(default=0)),
                ('caja', models.ForeignKey(related_name=b'moneycash_factura_caja', blank=True, to='moneycash.Caja', null=True)),
                ('cierre_caja', models.ForeignKey(related_name=b'moneycash_factura_cierre_caja', blank=True, to='moneycash.CierreCaja', null=True)),
                ('cliente', models.ForeignKey(blank=True, to='moneycash.Cliente', help_text=b'BUSCAR CLIENTE', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='factura_detalle',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigo', models.CharField(max_length=25, null=True, blank=True)),
                ('descripcion', models.CharField(max_length=100, null=True, blank=True)),
                ('cantidad', models.FloatField(default=0)),
                ('descuento_unitario', models.FloatField(default=0)),
                ('precio_unitario', models.FloatField(default=0)),
                ('costo_unitario', models.FloatField(default=0)),
                ('precio_descontado', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('descuento_total', models.FloatField(default=0)),
                ('precio_descontado_total', models.FloatField(default=0)),
                ('costo_total', models.FloatField(default=0)),
                ('utilidad', models.FloatField(default=0)),
                ('categoria', models.ForeignKey(blank=True, to='moneycash.Categoria', null=True)),
                ('factura', models.ForeignKey(to='moneycash.Factura')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos y/o servicios',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('existencias', models.FloatField(default=0)),
                ('descuento', models.FloatField(default=0)),
                ('precio', models.FloatField(default=0)),
                ('costo', models.FloatField(default=0)),
                ('categoria', models.ForeignKey(to='moneycash.Categoria')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('capitalizable', models.BooleanField(default=True, help_text=b'indica si este tipo de pago aplica en el cierre de caja')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField()),
                ('cerrado', models.BooleanField(default=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('fecha', models.DateField()),
                ('numero', models.PositiveIntegerField(null=True, blank=True)),
                ('autorizado', models.BooleanField(default=False)),
                ('impreso', models.BooleanField(default=False)),
                ('contabilizado', models.BooleanField(default=False)),
                ('entregado', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=100, null=True, blank=True)),
                ('concepto', models.CharField(max_length=200, null=True, blank=True)),
                ('monto', models.FloatField(default=0)),
                ('caja', models.ForeignKey(related_name=b'moneycash_recibo_caja', blank=True, to='moneycash.Caja', null=True)),
                ('cierre_caja', models.ForeignKey(related_name=b'moneycash_recibo_cierre_caja', blank=True, to='moneycash.CierreCaja', null=True)),
                ('cliente', models.ForeignKey(blank=True, to='moneycash.Cliente', null=True)),
                ('periodo', models.ForeignKey(related_name=b'moneycash_recibo_periodo', blank=True, to='moneycash.Periodo', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('numero_inicial', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'sucursales',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='recibo',
            name='sucursal',
            field=models.ForeignKey(related_name=b'moneycash_recibo_sucursal', blank=True, to='moneycash.Sucursal', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='recibo',
            name='user',
            field=models.ForeignKey(related_name=b'moneycash_recibo_user', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='item',
            name='marca',
            field=models.ForeignKey(to='moneycash.Marca'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='factura_detalle',
            name='item',
            field=models.ForeignKey(blank=True, to='moneycash.Item', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='factura_detalle',
            name='marca',
            field=models.ForeignKey(blank=True, to='moneycash.Marca', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='factura',
            name='periodo',
            field=models.ForeignKey(related_name=b'moneycash_factura_periodo', blank=True, to='moneycash.Periodo', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='factura',
            name='serie',
            field=models.ForeignKey(blank=True, to='moneycash.Serie', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='factura',
            name='sucursal',
            field=models.ForeignKey(related_name=b'moneycash_factura_sucursal', blank=True, to='moneycash.Sucursal', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='factura',
            name='user',
            field=models.ForeignKey(related_name=b'moneycash_factura_user', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='detalle_pago',
            name='factura',
            field=models.ForeignKey(blank=True, to='moneycash.Factura', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='detalle_pago',
            name='moneda',
            field=models.ForeignKey(to='moneycash.Moneda'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='detalle_pago',
            name='pago',
            field=models.ForeignKey(to='moneycash.Pago'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='detalle_pago',
            name='recibo',
            field=models.ForeignKey(blank=True, to='moneycash.Recibo', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='deposito',
            name='moneda',
            field=models.ForeignKey(related_name=b'moneycash_deposito_caja', default=1, to='moneycash.Moneda'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='deposito',
            name='periodo',
            field=models.ForeignKey(related_name=b'moneycash_deposito_periodo', blank=True, to='moneycash.Periodo', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='deposito',
            name='sucursal',
            field=models.ForeignKey(related_name=b'moneycash_deposito_sucursal', blank=True, to='moneycash.Sucursal', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='deposito',
            name='user',
            field=models.ForeignKey(related_name=b'moneycash_deposito_user', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='periodo',
            field=models.ForeignKey(related_name=b'moneycash_cierrecaja_periodo', blank=True, to='moneycash.Periodo', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='sucursal',
            field=models.ForeignKey(related_name=b'moneycash_cierrecaja_sucursal', blank=True, to='moneycash.Sucursal', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='user',
            field=models.ForeignKey(related_name=b'moneycash_cierrecaja_user', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='caja',
            name='series',
            field=models.ManyToManyField(to='moneycash.Serie'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='caja',
            name='sucursal',
            field=models.ForeignKey(to='moneycash.Sucursal'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodega',
            name='sucursal',
            field=models.ForeignKey(to='moneycash.Sucursal'),
            preserve_default=True,
        ),
    ]
